site_name: foobartory
repo_url: https://github.com/phptib/foobartory
edit_uri: blob/main/back/docs
# By default, we have URL like /api-guide/ intead of /api-guide.html,
# but it's not compatible with static builds made by `mkdocs build`.
use_directory_urls: false

watch:
  - docs
  - mkdocs.yml

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Open Sans
    code: Fira Code
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
#    - search.highlight
    - search.suggest
    - toc.follow

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Reference: reference.md

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      style_plain_text: python
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: [ !relative $config_dir ]
      restrict_base_path: false
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      # Slugify URL without only the tab title and not its identifier.
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - toc:
      permalink: "¤"
